### PR TITLE
✨ 1.0.2

### PR DESCRIPTION
**Pull request by Lebyy**
Planning to add more methods and some bug fixes.

### CODE REVIEW

**Comment by Lebyy** [comment]
Hi delta AlterSpace is me lebyy

**Comment by Lebyy** [comment]
Any thoughts? It'll log the response of node-fetch.

**Comment by Lebyy** [comment]
Planning to add the ability to switch between different HTTP client's

**Review by sbdh11 — APPROVED** [review]

**Comment by Lebyy** [comment]
Regarding #3 there will be an example discord.js bot soon.

**Pull request merged**
